/*
@TargetNode='localhost'
@GeneratedBy=brett.odgers-jewell
@GenerationDate=06/03/2020 16:27:15
@GenerationHost=WIN-3LNNL2AVMU
*/

instance of MSFT_Credential as $MSFT_Credential1ref
{
UserName = "\\bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xWaitForADDomain as $MSFT_xWaitForADDomain1ref
{
RetryIntervalSec = 30;
 RetryCount = 20;
 DomainName = "bojdomain.com.au";
 ModuleName = "xActiveDirectory";
 ModuleVersion = "3.0.0.0";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\adfs.ps1::29::9::xWaitForADDomain";
 ResourceID = "[xWaitForADDomain]DscForestWait";
 DomainUserCredential = $MSFT_Credential1ref;
 ConfigurationName = "ADFSInit";
};
instance of MSFT_Credential as $MSFT_Credential2ref
{
UserName = "\\bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xComputer as $MSFT_xComputer1ref
{
ResourceID = "[xComputer]JoinDomain";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\adfs.ps1::37::9::xComputer";
 DomainName = "bojdomain.com.au";
 Credential = $MSFT_Credential2ref;
 ModuleName = "xComputerManagement";
 ModuleVersion = "4.1.0.0";
 Name = "adfs";

DependsOn = {
    "[xWaitForADDomain]DscForestWait"};
 ConfigurationName = "ADFSInit";
};
instance of MSFT_xPendingReboot as $MSFT_xPendingReboot1ref
{
ModuleVersion = "0.4.0.0";
 ResourceID = "[xPendingReboot]Reboot1";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\adfs.ps1::45::9::xPendingReboot";
 Name = "RebootServer";
 ModuleName = "xPendingReboot";

DependsOn = {
    "[xComputer]JoinDomain"};
 ConfigurationName = "ADFSInit";
};
instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]installADFS";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\adfs.ps1::51::9::WindowsFeature";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 Name = "ADFS-Federation";

ModuleVersion = "1.0";
DependsOn = {
    "[xPendingReboot]Reboot1"};
 ConfigurationName = "ADFSInit";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="brett.odgers-jewell";

                        GenerationDate="06/03/2020 16:27:15";

                        GenerationHost="WIN-3LNNL2AVMU";

                        Name="ADFSInit";

                    };
