/*
@TargetNode='localhost'
@GeneratedBy=brett.odgers-jewell
@GenerationDate=06/02/2020 16:22:10
@GenerationHost=WIN-3LNNL2AVMU
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]ADDSFeatureInstall";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::26::9::WindowsFeature";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 Name = "AD-Domain-Services";

ModuleVersion = "1.0";
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential1ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_Credential as $MSFT_Credential2ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xADDomain as $MSFT_xADDomain1ref
{
DomainNetbiosName = "bojdomain";
 ForestMode = "WinThreshold";
 DomainName = "bojdomain.com.au";
 DomainAdministratorCredential = $MSFT_Credential1ref;
 SafemodeAdministratorPassword = $MSFT_Credential2ref;
 ModuleName = "xActiveDirectory";
 DomainMode = "WinThreshold";
 ModuleVersion = "3.0.0.0";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::32::9::xADDomain";
 ResourceID = "[xADDomain]ADDomainInstall";

DependsOn = {
    "[WindowsFeature]ADDSFeatureInstall"};
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential3ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xWaitForADDomain as $MSFT_xWaitForADDomain1ref
{
RetryIntervalSec = 60;
 RetryCount = 10;
 DomainName = "bojdomain.com.au";
 RebootRetryCount = 2;
 ModuleName = "xActiveDirectory";
 ModuleVersion = "3.0.0.0";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::42::9::xWaitForADDomain";
 ResourceID = "[xWaitForADDomain]WaitForDomainInstall";
 DomainUserCredential = $MSFT_Credential3ref;

DependsOn = {
    "[xADDomain]ADDomainInstall"};
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential4ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xADOrganizationalUnit as $MSFT_xADOrganizationalUnit1ref
{
Credential = $MSFT_Credential4ref;
 ResourceID = "[xADOrganizationalUnit]CreateAccountsOU";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::51::9::xADOrganizationalUnit";
 Ensure = "Present";
 ModuleName = "xActiveDirectory";
 Path = "DC=bojdomain,DC=com,DC=au";
 ModuleVersion = "3.0.0.0";
 Name = "Accounts";

DependsOn = {
    "[xWaitForADDomain]WaitForDomainInstall"};
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential5ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xADOrganizationalUnit as $MSFT_xADOrganizationalUnit2ref
{
Credential = $MSFT_Credential5ref;
 ResourceID = "[xADOrganizationalUnit]AdminOU";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::59::9::xADOrganizationalUnit";
 Ensure = "Present";
 ModuleName = "xActiveDirectory";
 Path = "OU=Accounts,DC=bojdomain,DC=com,DC=au";
 ModuleVersion = "3.0.0.0";
 Name = "Admin";

DependsOn = {
    "[xADOrganizationalUnit]CreateAccountsOU"};
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential6ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xADOrganizationalUnit as $MSFT_xADOrganizationalUnit3ref
{
Credential = $MSFT_Credential6ref;
 ResourceID = "[xADOrganizationalUnit]BusinessOU";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::67::9::xADOrganizationalUnit";
 Ensure = "Present";
 ModuleName = "xActiveDirectory";
 Path = "OU=Accounts,DC=bojdomain,DC=com,DC=au";
 ModuleVersion = "3.0.0.0";
 Name = "Business";

DependsOn = {
    "[xADOrganizationalUnit]CreateAccountsOU"};
 ConfigurationName = "DomainInit";
};
instance of MSFT_Credential as $MSFT_Credential7ref
{
UserName = "bojadmin";
 Password = "Password@1234";

};

instance of MSFT_xADOrganizationalUnit as $MSFT_xADOrganizationalUnit4ref
{
Credential = $MSFT_Credential7ref;
 ResourceID = "[xADOrganizationalUnit]ServiceOU";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\addc.ps1::75::9::xADOrganizationalUnit";
 Ensure = "Present";
 ModuleName = "xActiveDirectory";
 Path = "OU=Accounts,DC=bojdomain,DC=com,DC=au";
 ModuleVersion = "3.0.0.0";
 Name = "Service";

DependsOn = {
    "[xADOrganizationalUnit]CreateAccountsOU"};
 ConfigurationName = "DomainInit";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="brett.odgers-jewell";

                        GenerationDate="06/02/2020 16:22:10";

                        GenerationHost="WIN-3LNNL2AVMU";

                        Name="DomainInit";

                    };
