/*
@TargetNode='vm-aadc'
@GeneratedBy=brett.odgers-jewell
@GenerationDate=06/08/2020 11:00:09
@GenerationHost=WIN-3LNNL2AVMU
*/

instance of MSFT_ScriptResource as $MSFT_ScriptResource1ref
{
ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Script]InstallAADConnect";
 SourceInfo = "C:\\repos\\azuread_adfs_jwt_token\\modules\\azure-automation-dsc-node-conf\\mof_files\\aadc.ps1::10::4::Script";
 SetScript = "\n        $AADConnectDLUrl=\"https://download.microsoft.com/download/B/0/0/B00291D0-5A83-4DE7-86F5-980BC00DE05A/AzureADConnect.msi\"\n\n        $exe=\"$env:SystemRoot\\system32\\msiexec.exe\"\n\n        $tempfile = [System.IO.Path]::GetTempFileName()\n        $folder = [System.IO.Path]::GetDirectoryName($tempfile)\n\n        $webclient = New-Object System.Net.WebClient\n        $webclient.DownloadFile($AADConnectDLUrl, $tempfile)\n\n        Rename-Item -Path $tempfile -NewName \"AzureADConnect.msi\"\n        $MSIPath = $folder + \"\\AzureADConnect.msi\"\n\n        Invoke-Expression \"& `\"$exe`\" /i $MSIPath /qn /passive /forcerestart\"\n    ";
 GetScript = " @{} ";
 TestScript = " \n        return Test-Path \"$env:TEMP\\AzureADConnect.msi\" \n    ";

ModuleVersion = "1.0";
 ConfigurationName = "aadcinit";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="brett.odgers-jewell";

                        GenerationDate="06/08/2020 11:00:09";

                        GenerationHost="WIN-3LNNL2AVMU";

                        Name="aadcinit";

                    };
