/*
@TargetNode='vm-adds'
@GeneratedBy=brett.odgers-jewell
@GenerationDate=06/28/2020 11:01:24
@GenerationHost=WIN-3LNNL2AVMU
*/

instance of MSFT_DSCMetaConfiguration as $MSFT_DSCMetaConfiguration1ref
{
RebootNodeIfNeeded = True;

};

instance of OMI_ConfigurationDocument
{
 Version="2.0.0";
 MinimumCompatibleVersion = "1.0.0";
 CompatibleVersionAdditionalProperties= { };
 Author="brett.odgers-jewell";
 GenerationDate="06/28/2020 11:01:24";
 GenerationHost="WIN-3LNNL2AVMU";
 Name="DomainInit";
};
